### PR TITLE
Update to 8.2

### PR DESCRIPTION
**Pull request by embeddedt**
@kisvegabor This isn't ready to be merged yet - there is an issue with DMA2D I need to track down. It crashes while rendering the initial screen and each pixel has another pixel-sized gap between them, so I'm guessing there's some mismatch in color modes. For now I've just disabled use of DMA2D.

I've also only tested with CMake as I recently reinstalled Linux and haven't had a chance to get CubeIDE again. Does someone have a copy of CubeIDE to quickly test with? If not, I can also test it later.

@GorgonMeducer If you have some time, could you pull this branch and update the IAR project to reflect the removal of `lv_demos`, please?

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
sure

**Comment by GorgonMeducer** [comment]
@embeddedt I didn't see the master branch updates to v8.2.0 and remove the lv_demos.

Can you update the master branch first?

**Comment by embeddedt** [comment]
The update is on the `update/8.2` branch; I haven't merged it yet because of the DMA issue I didn't had time to debug. If you'd rather wait for it to be in `master`, that's fine as well. :slightly_smiling_face:

**Comment by GorgonMeducer** [comment]
@embeddedt Aha...sorry, I misunderstood your original meaning. OK, I will pull the 8.2 branch.

**Comment by GorgonMeducer** [comment]
@embeddedt 

https://github.com/lvgl/lv_port_stm32f746_disco/pull/22

Done.

**Comment by embeddedt** [comment]
I have tracked down the DMA2D issue somewhat. The issue is that the OPFCCR register (which controls the color mode) is incorrectly being reset to 0 sometime between when `lv_draw_stm32_dma2d_init` and `lv_draw_stm32_dma2d_blend_fill` are called. I tried cleaning the cache at the end of `lv_draw_stm32_dma2d_init` but it didn't help.

The following patch hides the issue, but wasn't needed on 8.1, and the code path is nearly identical. Does anyone happen to know if STM32s are supposed to need this register reset on every transaction? 

```diff
diff --git a/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c b/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c
index 20344a56..9ed061f6 100644
--- a/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c
+++ b/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c
@@ -169,6 +169,7 @@ static void lv_draw_stm32_dma2d_blend_fill(lv_color_t * dest_buf, lv_coord_t des
     DMA2D->OCOLR = color.full;
     DMA2D->OOR = dest_stride - area_w;
     DMA2D->NLR = (area_w << DMA2D_NLR_PL_Pos) | (area_h << DMA2D_NLR_NL_Pos);
+    DMA2D->OPFCCR = LV_DMA2D_COLOR_FORMAT;
 
     /*start transfer*/
     DMA2D->CR |= DMA2D_CR_START_Msk;
@@ -185,6 +186,7 @@ static void lv_draw_stm32_dma2d_blend_map(lv_color_t * dest_buf, const lv_area_t
     int32_t dest_h = lv_area_get_height(dest_area);
 
     invalidate_cache();
+    DMA2D->OPFCCR = LV_DMA2D_COLOR_FORMAT;
     if(opa >= LV_OPA_MAX) {
         DMA2D->CR = 0;
         /*copy output colour mode, this register controls both input and output colour format*/
```

**Comment by kisvegabor** [comment]
In debug can you see if the value is still valid before the first call of `lv_timer_handler()`?

**Comment by embeddedt** [comment]
The issue has nothing to do with the hardware; I just seem to be blind and missed [this warning](https://github.com/lvgl/lvgl/blob/305ad00893c0d18d9a65e28ee03d65f76f8abb0a/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c#L81) about not enabling the DMA2D clock. :laughing: Sorry for wasting your time.

**Pull request merged**
